[package]
name = "jrpxy-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
jrpxy-body = { workspace = true }
jrpxy-http-message = { workspace = true }
jrpxy-util = { workspace = true }

thiserror = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }